# -*- coding: utf-8 -*-
"""세계도시 · 도시로봇·HRI 연구 데이터베이스 초기 시드.

RECORDS: [{subsystem, kind, slug, title, data:{...}}] — app.py가 dbrecords에 적재.
교차참조는 슬러그 문자열로 연결(프론트가 index로 하이퍼링크 해석).
서울 관련 항목은 최준영 박사의 실제 연구(성수동 자율주행 배송로봇 보행자 관찰조사,
전문가 AHP에서 보행안전 1순위, 지각된 안전·사람-로봇 코딩 신뢰도 이슈)와 연결.
"""

# ============================================================ World Cities
WORLD_CITIES = [
    {"slug": "seoul", "title": "Seoul", "data": {
        "name": "Seoul", "country": "South Korea", "region": "asia",
        "population": 9400000,
        "summary": "한국의 수도이자 고밀·고령화가 동시에 진행되는 글로벌 도시. 스마트도시 거버넌스, 보행친화 정책, 자율주행 배송로봇·돌봄로봇 실증이 활발해 도시로봇 연구의 핵심 맥락을 제공한다.",
        "smartCityRelevance": "S-DoT 도시데이터센서, 디지털 트윈(S-Map), 공공 마이데이터 등 도시 데이터 플랫폼이 고도화되어 있다.",
        "agingCityRelevance": "초고령사회 진입을 앞두고 있어 돌봄로봇·커뮤니티케어 수요가 크다.",
        "walkabilityRelevance": "보행 일상권·녹색교통진흥지역 등 보행친화 정책 추진. 보도 위 배송로봇과 보행자 상충이 현안.",
        "publicSpaceRelevance": "청계천 복원, 서울로7017 등 공공공간 재생 경험 풍부.",
        "careInfrastructureRelevance": "노인복지관·데이케어센터 등 돌봄 인프라가 조밀하여 돌봄로봇 실증지로 적합.",
        "urbanRobotRelevance": "성수·강남 등에서 자율주행 배송로봇 시범운행, 복지시설 돌봄로봇 도입이 진행 중.",
        "keyUrbanChallenges": ["급속한 고령화와 돌봄 부담", "보도 혼잡과 보행안전", "지역 간 접근성 격차", "기후위기 대응"],
        "keyPolicies": ["seoul-smart-city-sdot", "seoul-pedestrian-priority"],
        "relatedTopics": ["smart-city-governance", "aging-cities", "walkable-cities", "robot-friendly-cities"],
        "relatedRobotCases": ["seoul-delivery-robot-sidewalk-pilot", "seoul-care-robot-service-trial"],
        "sources": ["서울연구원 도시정보", "서울특별시 스마트도시 정책"]}},
    {"slug": "tokyo", "title": "Tokyo", "data": {
        "name": "Tokyo", "country": "Japan", "region": "asia", "population": 13960000,
        "summary": "세계 최고령 대도시 중 하나로 돌봄로봇·서비스로봇 도입의 선도 도시. 대중교통 중심의 고밀 보행도시.",
        "agingCityRelevance": "개호(介護) 로봇 보급 정책과 시설 도입 경험이 풍부.",
        "urbanRobotRelevance": "돌봄로봇·안내로봇 상용화 사례 다수. 보도 배송로봇 제도화 논의 진전.",
        "keyUrbanChallenges": ["초고령화", "돌봄 인력 부족", "재난 대응"],
        "relatedTopics": ["aging-cities", "smart-mobility"],
        "relatedRobotCases": ["tokyo-care-robot-eldercare"], "sources": []}},
    {"slug": "singapore", "title": "Singapore", "data": {
        "name": "Singapore", "country": "Singapore", "region": "asia", "population": 5640000,
        "summary": "Smart Nation 전략으로 도시 디지털화를 선도. 로봇 친화 인프라와 강한 거버넌스가 특징.",
        "smartCityRelevance": "Smart Nation, Virtual Singapore 디지털 트윈.",
        "urbanRobotRelevance": "배송·청소·순찰 로봇의 공공공간 시범운영을 제도적으로 지원.",
        "keyUrbanChallenges": ["토지 제약", "고령화", "노동력 부족"],
        "relatedTopics": ["smart-city-governance", "robot-friendly-cities", "urban-data-platforms"],
        "relatedRobotCases": ["singapore-delivery-robot-estate"], "sources": []}},
    {"slug": "helsinki", "title": "Helsinki", "data": {
        "name": "Helsinki", "country": "Finland", "region": "europe", "population": 660000,
        "summary": "사람 중심 스마트도시와 개방형 데이터·MaaS의 대표 도시. 신뢰 기반 디지털 거버넌스.",
        "smartCityRelevance": "오픈데이터·MyData, 시민 참여형 스마트도시.",
        "walkabilityRelevance": "겨울도시 보행환경과 MaaS 통합 모빌리티.",
        "urbanRobotRelevance": "보도 자율주행 셔틀·배송 파일럿 경험.",
        "relatedTopics": ["people-centered-smart-cities", "smart-mobility", "urban-data-platforms"],
        "relatedRobotCases": [], "sources": []}},
    {"slug": "barcelona", "title": "Barcelona", "data": {
        "name": "Barcelona", "country": "Spain", "region": "europe", "population": 1620000,
        "summary": "수퍼블록(Superilla)으로 보행·공공공간을 재편한 도시. 기술주권·시민데이터 거버넌스 선도.",
        "walkabilityRelevance": "수퍼블록으로 차량을 줄이고 보행·놀이 공간 확대.",
        "publicSpaceRelevance": "가로 공간의 보행자 우선 재배분 실험.",
        "smartCityRelevance": "Decidim 시민참여 플랫폼, 데이터 주권 정책.",
        "relatedTopics": ["walkable-cities", "urban-public-space", "people-centered-smart-cities"],
        "relatedRobotCases": [], "keyPolicies": ["barcelona-superblocks"], "sources": []}},
    {"slug": "dubai", "title": "Dubai", "data": {
        "name": "Dubai", "country": "United Arab Emirates", "region": "middle_east", "population": 3550000,
        "summary": "정부 주도 첨단기술 도입과 자율주행·드론·로봇 서비스 목표가 명확한 도시.",
        "smartCityRelevance": "Smart Dubai, 자율주행·서비스로봇 정부 전략.",
        "urbanRobotRelevance": "배송·순찰 로봇 도입 목표가 정책에 명시.",
        "relatedTopics": ["smart-city-governance", "robot-friendly-cities"], "relatedRobotCases": [], "sources": []}},
    {"slug": "amsterdam", "title": "Amsterdam", "data": {
        "name": "Amsterdam", "country": "Netherlands", "region": "europe", "population": 920000,
        "summary": "자전거·보행 중심 모빌리티와 책임있는 AI·알고리즘 등록부로 알려진 도시.",
        "walkabilityRelevance": "자전거·보행 우선 가로망.",
        "smartCityRelevance": "알고리즘 등록부 등 책임있는 디지털 거버넌스.",
        "relatedTopics": ["walkable-cities", "smart-mobility", "digital-inclusion"], "relatedRobotCases": [], "sources": []}},
    {"slug": "medellin", "title": "Medellín", "data": {
        "name": "Medellín", "country": "Colombia", "region": "latin_america", "population": 2530000,
        "summary": "사회적 도시계획과 케이블카·에스컬레이터 등 포용적 모빌리티로 변모한 도시.",
        "walkabilityRelevance": "경사지 포용적 보행·이동 인프라.",
        "keyUrbanChallenges": ["불평등", "비공식 정주지 접근성"],
        "relatedTopics": ["smart-mobility", "digital-inclusion"], "relatedRobotCases": [], "sources": []}},
    {"slug": "kigali", "title": "Kigali", "data": {
        "name": "Kigali", "country": "Rwanda", "region": "africa", "population": 1130000,
        "summary": "드론 의료물류(Zipline)로 유명한 아프리카의 혁신 도시. 청결·질서 도시정책.",
        "urbanRobotRelevance": "드론 기반 의료물품 배송으로 자율 물류의 도시 적용 선도.",
        "keyUrbanChallenges": ["급속한 도시화", "기반시설 격차"],
        "relatedTopics": ["smart-mobility", "robot-friendly-cities"], "relatedRobotCases": [], "sources": []}},
    {"slug": "taipei", "title": "Taipei", "data": {
        "name": "Taipei", "country": "Taiwan", "region": "asia", "population": 2600000,
        "summary": "고밀 보행·대중교통 도시이자 스마트도시 실증(SmartCity PoC) 활발.",
        "smartCityRelevance": "Taipei Smart City PoC 플랫폼으로 다수 실증.",
        "agingCityRelevance": "고령화 대응 커뮤니티케어 확대.",
        "relatedTopics": ["smart-city-governance", "aging-cities", "walkable-cities"], "relatedRobotCases": [], "sources": []}},
]

WORLD_TOPICS = [
    ("global-smart-cities", "Global Smart Cities", "global", "전 세계 스마트도시 전략의 비교와 공통 원리.",
     ["기술중심 vs 사람중심", "데이터 거버넌스", "상호운용성"]),
    ("people-centered-smart-cities", "People-Centered Smart Cities", "inclusion", "기술보다 시민·삶의 질을 우선하는 스마트도시 패러다임.",
     ["시민참여", "디지털 권리", "포용"]),
    ("aging-cities", "Aging Cities", "aging", "고령화에 대응하는 도시계획·돌봄 인프라·기술.",
     ["돌봄 부담", "연령친화도시", "돌봄로봇 수용성"]),
    ("walkable-cities", "Walkable Cities", "public_space", "보행 중심의 도시 공간과 안전·접근성.",
     ["보행안전", "15분 도시", "보도 상충(로봇·자전거)"]),
    ("urban-public-space", "Urban Public Space", "public_space", "공공공간의 질과 재생, 다용도 활용.",
     ["공공공간 재배분", "포용적 설계", "안전"]),
    ("smart-mobility", "Smart Mobility", "mobility", "MaaS·자율주행·마이크로모빌리티 등 지능형 이동.",
     ["MaaS", "자율주행", "라스트마일 배송"]),
    ("urban-data-platforms", "Urban Data Platforms", "data", "도시 데이터 수집·통합·개방 플랫폼.",
     ["디지털 트윈", "오픈데이터", "센서 거버넌스"]),
    ("smart-city-governance", "Smart City Governance", "governance", "스마트도시의 의사결정·규제·시민참여 구조.",
     ["규제 샌드박스", "데이터 주권", "책임있는 AI"]),
    ("digital-inclusion", "Digital Inclusion", "inclusion", "디지털 격차 해소와 포용적 서비스 접근.",
     ["접근성", "디지털 리터러시", "취약계층"]),
    ("robot-friendly-cities", "Robot-Friendly Cities", "robotics", "로봇이 안전하게 운용되도록 설계된 도시 인프라·제도.",
     ["보도 운행 거버넌스", "로봇 인프라 표준", "안전·책임"]),
]

WORLD_CASES = [
    {"slug": "seoul-sungsu-delivery-robot-observation", "title": "Seoul Sungsu-dong Delivery Robot–Pedestrian Observation",
     "data": {"cityId": "seoul", "country": "South Korea", "region": "asia", "caseType": "robot_testbed",
        "summary": "성수동 일대에서 자율주행 배송로봇과 보행자의 상호작용을 5일간 현장 관찰(242건)하고 전문가 AHP를 병행한 실증 연구.",
        "urbanProblem": "보도 위에서 배송로봇과 보행자가 공간을 공유하며 발생하는 보행안전·상충 문제.",
        "intervention": "현장 관찰 코딩 + 전문가 AHP로 보도 운행의 우선가치(보행안전 1순위)와 상충 패턴을 도출.",
        "actors": ["서울시립대 연구팀", "로봇 운영사", "지자체"],
        "technologies": ["자율주행 배송로봇", "영상 관찰", "AHP"],
        "outcomes": "전문가 AHP에서 보행안전이 최우선 가치로 도출. 사람·로봇 행동 코딩의 관찰자 간 신뢰도(κ) 확보가 과제로 확인됨.",
        "evidenceLevel": "moderate",
        "relevanceToDeliveryRobots": "보도 운행 가이드라인·지각된 안전 설계의 실증 근거.",
        "relevanceToHRI": "현장 관찰 기반 HRI 방법론(코딩·신뢰도) 사례.",
        "relatedRobotCases": ["seoul-delivery-robot-sidewalk-pilot"],
        "sources": ["성수동 ADR 보행자 관찰조사(2024)"]}},
    {"slug": "barcelona-superblocks", "title": "Barcelona Superblocks (Superilles)",
     "data": {"cityId": "barcelona", "country": "Spain", "region": "europe", "caseType": "public_space",
        "summary": "블록 단위로 통과교통을 제한해 보행·공공공간을 회복한 도시설계 실험.",
        "urbanProblem": "차량 중심 가로로 인한 대기오염·소음·보행공간 부족.",
        "intervention": "수퍼블록 내부 차량 통행 제한, 보행·놀이·녹지 공간으로 전환.",
        "actors": ["바르셀로나시", "주민"], "technologies": ["교통관리", "공공공간 설계"],
        "outcomes": "보행공간·녹지 증가, 대기질·활동 개선 보고.", "evidenceLevel": "strong",
        "relevanceToDeliveryRobots": "보행자 우선 공간에서 로봇 운행 규칙 설계의 참고.",
        "relatedTopics": ["walkable-cities", "urban-public-space"], "sources": []}},
    {"slug": "helsinki-maas-whim", "title": "Helsinki MaaS (Whim)",
     "data": {"cityId": "helsinki", "country": "Finland", "region": "europe", "caseType": "smart_mobility",
        "summary": "대중교통·택시·공유 모빌리티를 하나의 구독형 서비스로 통합한 MaaS 사례.",
        "urbanProblem": "분절된 교통수단과 자가용 의존.", "intervention": "통합 결제·경로 앱으로 멀티모달 이동 제공.",
        "actors": ["MaaS Global", "헬싱키 교통당국"], "technologies": ["MaaS 플랫폼", "오픈 API"],
        "outcomes": "멀티모달 이용 증가 보고.", "evidenceLevel": "moderate",
        "relatedTopics": ["smart-mobility", "urban-data-platforms"], "sources": []}},
    {"slug": "singapore-virtual-singapore", "title": "Virtual Singapore (Digital Twin)",
     "data": {"cityId": "singapore", "country": "Singapore", "region": "asia", "caseType": "urban_data_platform",
        "summary": "도시 전체의 3D 디지털 트윈으로 계획·시뮬레이션·운영을 지원.",
        "urbanProblem": "복잡한 도시 시스템의 통합 의사결정 어려움.", "intervention": "3D 디지털 트윈 플랫폼 구축.",
        "actors": ["싱가포르 정부"], "technologies": ["디지털 트윈", "3D GIS"],
        "outcomes": "계획·재난·인프라 시뮬레이션 활용.", "evidenceLevel": "moderate",
        "relevanceToDeliveryRobots": "로봇 운행 경로·공간 시뮬레이션 기반.",
        "relatedTopics": ["urban-data-platforms", "robot-friendly-cities"], "sources": []}},
    {"slug": "kigali-zipline-drone", "title": "Kigali Zipline Medical Drone Delivery",
     "data": {"cityId": "kigali", "country": "Rwanda", "region": "africa", "caseType": "robot_testbed",
        "summary": "드론으로 혈액·의약품을 원격지에 배송하는 자율 물류 시스템.",
        "urbanProblem": "의료물자 적시 공급의 접근성 한계.", "intervention": "드론 자율배송 네트워크 운영.",
        "actors": ["Zipline", "르완다 정부"], "technologies": ["배송 드론", "자율항법"],
        "outcomes": "배송시간 단축·의료 접근성 개선 보고.", "evidenceLevel": "strong",
        "relevanceToDeliveryRobots": "자율 배송의 공공 편익·수용성 사례.",
        "relatedTopics": ["smart-mobility", "robot-friendly-cities"], "sources": []}},
]

WORLD_POLICIES = [
    {"slug": "seoul-smart-city-sdot", "title": "Seoul S-DoT Urban Data Sensor Network",
     "data": {"cityId": "seoul", "country": "South Korea", "region": "asia", "policyDomain": "data_platform",
        "period": "2019–", "leadOrganization": "서울특별시",
        "summary": "도시 곳곳에 설치한 복합센서(S-DoT)로 환경·이동 데이터를 수집·개방하는 도시데이터 정책.",
        "objectives": ["도시 데이터 기반 행정", "데이터 개방", "현장 기반 정책"],
        "policyInstruments": ["복합센서 설치", "데이터 플랫폼", "오픈데이터"],
        "implementationStatus": "ongoing",
        "relevanceToUrbanRobotics": "로봇 운행 환경(혼잡·보행) 데이터의 잠재적 기반.",
        "relevanceToSeoul": "데이터 기반 보행·로봇 정책 설계 근거.",
        "sources": ["서울특별시 스마트도시 정책"]}},
    {"slug": "seoul-pedestrian-priority", "title": "Seoul Pedestrian-Priority & Safety Policy",
     "data": {"cityId": "seoul", "country": "South Korea", "region": "asia", "policyDomain": "mobility",
        "period": "2010s–", "leadOrganization": "서울특별시",
        "summary": "보행권 조례·생활권 보행환경 개선 등 보행자 우선 정책 기조.",
        "objectives": ["보행안전", "보행 접근성", "차량 속도 저감"],
        "policyInstruments": ["보행자 우선도로", "속도관리", "보행환경 개선사업"],
        "implementationStatus": "ongoing",
        "relevanceToUrbanRobotics": "보도 위 배송로봇 운행 규칙과 직접 충돌·연계되는 정책영역.",
        "relevanceToSeoul": "로봇-보행자 상충 관리의 제도 기반.",
        "sources": []}},
    {"slug": "korea-sidewalk-robot-act", "title": "Korea Sidewalk Delivery Robot Legalization (2023)",
     "data": {"country": "South Korea", "region": "asia", "policyDomain": "robotics",
        "period": "2023–", "leadOrganization": "대한민국 정부(지능형로봇법·도로교통법 개정)",
        "summary": "실외 자율주행 배송로봇의 보도 통행을 제도적으로 허용한 법 개정.",
        "objectives": ["배송로봇 상용화 기반", "안전 운행 기준", "보험·책임 체계"],
        "policyInstruments": ["보도 통행 허용", "운행안전인증", "보험 의무"],
        "implementationStatus": "ongoing",
        "relevanceToUrbanRobotics": "배송로봇 보도 운행의 법적 근거 — 사이드워크 거버넌스의 핵심.",
        "relevanceToSeoul": "성수동 등 실증·확산의 제도적 토대.",
        "sources": []}},
    {"slug": "japan-care-robot-policy", "title": "Japan Nursing-Care Robot Promotion Policy",
     "data": {"cityId": "tokyo", "country": "Japan", "region": "asia", "policyDomain": "care",
        "period": "2013–", "leadOrganization": "일본 후생노동성·경제산업성",
        "summary": "돌봄(개호) 로봇 개발·도입을 보조금·기준으로 촉진한 정책.",
        "objectives": ["돌봄 인력 부담 경감", "돌봄로봇 보급", "안전기준"],
        "policyInstruments": ["보조금", "도입 가이드", "안전·효과 평가"],
        "implementationStatus": "ongoing",
        "relevanceToUrbanRobotics": "돌봄로봇 수용성·도입 정책의 국제 비교 기준.",
        "sources": []}},
]

# ============================================================ Urban Robotics & HRI
ROBOT_TYPES = [
    {"slug": "autonomous-delivery-robots", "title": "Autonomous Delivery Robots", "data": {
        "robotCategory": "autonomous_delivery_robot",
        "definition": "도시 환경에서 라스트마일 배송을 수행하는 자율·반자율 이동로봇.",
        "urbanContext": ["보도(sidewalk)", "캠퍼스", "상업지구", "주거지"],
        "mainUsers": ["보행자", "배송 운영자", "지역 주민", "리테일 이용자"],
        "hriIssues": ["지각된 안전", "보행자 회피", "신뢰", "양보 행동", "공공 수용성"],
        "policyIssues": ["보도 거버넌스", "책임/배상", "보험", "속도 규제", "프라이버시"],
        "safetyIssues": ["근접 통과", "급정지", "충돌·전도", "취약보행자(아동·고령) 안전"],
        "privacyIssues": ["주행 영상 촬영", "보행자 식별 가능성"],
        "relatedCities": ["seoul", "singapore"],
        "relatedCases": ["seoul-delivery-robot-sidewalk-pilot", "singapore-delivery-robot-estate"],
        "sources": []}},
    {"slug": "care-robots", "title": "Care Robots", "data": {
        "robotCategory": "care_robot",
        "definition": "고령자·돌봄제공자·가족·돌봄기관을 보조·모니터링·소통·정서지원으로 돕는 로봇.",
        "urbanContext": ["가정", "노인복지관", "요양원", "병원", "커뮤니티케어"],
        "mainUsers": ["고령자", "돌봄제공자", "가족", "시설 종사자"],
        "hriIssues": ["신뢰", "수용성", "사회적 실재감", "프라이버시", "정서반응", "돌봄부담"],
        "policyIssues": ["돌봄 윤리", "데이터 거버넌스", "안전", "조달", "서비스 통합"],
        "safetyIssues": ["물리적 접촉 안전", "오작동", "낙상 위험 상황"],
        "privacyIssues": ["가정 내 모니터링", "건강·민감정보"],
        "relatedCities": ["tokyo", "seoul"],
        "relatedCases": ["seoul-care-robot-service-trial", "tokyo-care-robot-eldercare"],
        "sources": []}},
]

ROBOT_CASES = [
    {"slug": "seoul-delivery-robot-sidewalk-pilot", "title": "Seoul Delivery Robot Sidewalk Pilot", "data": {
        "robotType": "autonomous_delivery_robot", "cityId": "seoul", "cityName": "Seoul",
        "country": "South Korea", "region": "asia", "deploymentSpace": "sidewalk",
        "operator": "민간 로봇 운영사", "manufacturer": "국내 로봇 제조사", "deploymentPeriod": "2023–",
        "useCase": "보도를 활용한 근거리 음식·물품 라스트마일 배송.",
        "targetUsers": ["보행자", "주문 고객", "운영자"],
        "serviceFunction": ["음식 배송", "소포 배송"],
        "hriFocus": ["지각된 안전", "보행자 양보·회피", "공공공간 수용성"],
        "observedInteractions": ["상호 양보", "근접 회피", "정지 대치", "주시·촬영"],
        "evaluationMethods": ["현장 관찰", "영상 코딩", "인터셉트 설문"],
        "policyIssues": ["보도 운행 규칙", "속도 제한", "책임/보험"],
        "safetyIssues": ["좁은 보도 근접 통과", "취약보행자 상충"],
        "privacyIssues": ["주행 영상 촬영"],
        "evidenceLevel": "moderate",
        "researchValue": "보도 운행 거버넌스와 지각된 안전 설계의 실증 사례. 성수동 관찰연구의 현장 기반.",
        "relevanceToSeoul": "보행친화 정책과 배송로봇 운행의 상충/조화 설계에 직접 기여.",
        "relatedStudyDesigns": ["field-observation-delivery-robot-pedestrian", "video-coding-sidewalk-delivery-robot",
                                 "scenario-experiment-delivery-robot-ehmi"],
        "sources": ["seoul-sungsu-delivery-robot-observation"]}},
    {"slug": "seoul-care-robot-service-trial", "title": "Seoul Care Robot Service Trial", "data": {
        "robotType": "care_robot", "cityId": "seoul", "cityName": "Seoul", "country": "South Korea", "region": "asia",
        "deploymentSpace": "welfare_center", "operator": "지자체·복지기관", "deploymentPeriod": "2020s",
        "useCase": "노인복지관·가정에서 정서지원·안부확인·생활보조를 제공하는 돌봄로봇 시범.",
        "targetUsers": ["고령자", "돌봄제공자", "복지관 종사자"],
        "serviceFunction": ["안부 확인", "정서적 교감", "복약·일정 알림"],
        "hriFocus": ["신뢰", "수용성", "사회적 실재감", "돌봄부담 경감"],
        "observedInteractions": ["대화·교감", "알림 응답", "반복 사용 중 적응"],
        "evaluationMethods": ["수용성 설문", "심층면접", "장기 사용 관찰"],
        "policyIssues": ["돌봄 윤리", "데이터 거버넌스", "서비스 연계"],
        "privacyIssues": ["가정 내 모니터링", "건강정보"],
        "evidenceLevel": "moderate",
        "researchValue": "고령자 돌봄로봇 수용성·장기 상호작용 연구의 도시 맥락.",
        "relevanceToSeoul": "초고령사회 대비 커뮤니티케어와 돌봄로봇 통합 모델.",
        "relatedStudyDesigns": ["care-robot-trust-experiment-older-adults", "care-robot-acceptance-welfare-center",
                                 "longitudinal-care-robot-use"],
        "sources": []}},
    {"slug": "singapore-delivery-robot-estate", "title": "Singapore Estate Delivery Robot Service", "data": {
        "robotType": "autonomous_delivery_robot", "cityId": "singapore", "cityName": "Singapore",
        "country": "Singapore", "region": "asia", "deploymentSpace": "residential_area",
        "operator": "주택단지 운영주체", "deploymentPeriod": "2021–",
        "useCase": "공공주택 단지 내 자율 배송 서비스.",
        "targetUsers": ["주민", "배송 운영자"], "serviceFunction": ["택배·식음료 배송"],
        "hriFocus": ["수용성", "신뢰", "고령 주민 접근성"],
        "evaluationMethods": ["이용 로그", "주민 설문"],
        "policyIssues": ["단지 내 운행 규칙", "엘리베이터·출입 연동"],
        "evidenceLevel": "moderate",
        "researchValue": "제도적으로 지원되는 로봇 친화 단지의 운영 모델.",
        "relatedStudyDesigns": [], "sources": []}},
    {"slug": "tokyo-care-robot-eldercare", "title": "Tokyo Eldercare Robot Deployment", "data": {
        "robotType": "care_robot", "cityId": "tokyo", "cityName": "Tokyo", "country": "Japan", "region": "asia",
        "deploymentSpace": "nursing_home", "operator": "요양시설", "deploymentPeriod": "2015–",
        "useCase": "요양시설에서 이동보조·모니터링·정서지원을 수행하는 개호로봇.",
        "targetUsers": ["고령자", "요양보호사"], "serviceFunction": ["이동 보조", "모니터링", "레크리에이션"],
        "hriFocus": ["수용성", "돌봄부담", "정서반응"],
        "evaluationMethods": ["종사자 설문", "관찰", "효과성 평가"],
        "policyIssues": ["조달", "안전기준", "보조금"],
        "evidenceLevel": "moderate",
        "researchValue": "세계 최고령 도시의 돌봄로봇 제도화·도입 경험.",
        "relevanceToSeoul": "돌봄로봇 도입 정책·수용성의 국제 비교 기준.",
        "relatedStudyDesigns": ["longitudinal-care-robot-use"], "sources": []}},
    {"slug": "us-campus-delivery-robots", "title": "US Campus Delivery Robots", "data": {
        "robotType": "autonomous_delivery_robot", "country": "United States", "region": "north_america",
        "deploymentSpace": "campus", "operator": "캠퍼스 사업자", "deploymentPeriod": "2019–",
        "useCase": "대학 캠퍼스 내 음식·소포 자율 배송.",
        "targetUsers": ["학생", "교직원"], "serviceFunction": ["음식 배송"],
        "hriFocus": ["수용성", "보행자 상호작용", "신기성(novelty) 효과"],
        "evaluationMethods": ["이용 로그", "설문", "관찰"],
        "policyIssues": ["캠퍼스 보행로 운행", "접근성(장애인)"],
        "evidenceLevel": "moderate",
        "researchValue": "통제된 보행환경에서의 대규모 수용성·상호작용 데이터.",
        "relatedStudyDesigns": ["field-observation-delivery-robot-pedestrian"], "sources": []}},
    {"slug": "incheon-airport-guide-robot", "title": "Incheon Airport Guide/Service Robot", "data": {
        "robotType": "autonomous_delivery_robot", "cityId": "seoul", "cityName": "Incheon", "country": "South Korea",
        "region": "asia", "deploymentSpace": "public_facility", "operator": "공항공사", "deploymentPeriod": "2017–",
        "useCase": "공항 내 안내·순찰·경량 배송 서비스 로봇.",
        "targetUsers": ["여행객"], "serviceFunction": ["길안내", "정보제공", "경량 운반"],
        "hriFocus": ["접근성", "다국어 상호작용", "혼잡 공간 회피"],
        "evaluationMethods": ["이용 관찰", "만족도 설문"],
        "policyIssues": ["혼잡 공공시설 운행"], "evidenceLevel": "weak",
        "researchValue": "고밀 공공시설에서의 서비스로봇-군중 상호작용 사례.",
        "relatedStudyDesigns": [], "sources": []}},
]

HRI_CONSTRUCTS = [
    ("trust-in-hri", "Trust in HRI", "trust", "both",
     "로봇의 능력·의도·신뢰성에 대한 이용자의 기대와 의존 의향.",
     ["의존 행동", "지시 수용", "재이용 의향"], ["신뢰 척도(Trust in Automation 등)"],
     ["어떤 상황에서 로봇을 신뢰/불신했는가?"], ["로봇 신뢰성 조작(오류율)"]),
    ("perceived-safety", "Perceived Safety", "perceived_safety", "both",
     "로봇과 상호작용·공존 시 이용자가 느끼는 주관적 안전감. 배송로봇 보도 연구의 핵심 변수.",
     ["회피 거리", "긴장·놀람 반응", "주관적 안전 평정"], ["지각된 안전 설문 문항"],
     ["로봇이 가까이 왔을 때 위험을 느꼈는가?"], ["근접 거리·속도 조작"]),
    ("acceptance", "Robot Acceptance", "acceptance", "both",
     "로봇 도입·사용에 대한 수용 태도와 사용 의도(UTAUT/TAM 기반).",
     ["사용 의도", "추천 의향"], ["수용성(UTAUT) 척도"],
     ["이 로봇을 일상에서 쓸 의향이 있는가?"], ["유용성·용이성 메시지 조작"]),
    ("usability", "Usability", "usability", "both",
     "로봇 서비스의 사용 용이성·효율·만족.",
     ["과업 완수율", "오류·도움요청"], ["SUS 등 사용성 척도"], ["사용이 쉬웠는가?"], ["인터페이스 설계"]),
    ("social-presence", "Social Presence", "social_presence", "care_robot",
     "로봇을 사회적 존재로 느끼는 정도.",
     ["대화 지속", "호칭·의인화 표현"], ["사회적 실재감 척도"], ["로봇이 함께 있는 느낌이었는가?"], ["의인화 단서(음성·표정)"]),
    ("anthropomorphism", "Anthropomorphism", "anthropomorphism", "both",
     "로봇에 인간적 속성을 부여하는 경향.",
     ["인격 부여 발화"], ["Godspeed 의인화 하위척도"], ["로봇이 사람처럼 느껴졌는가?"], ["외형·행동 의인화 수준"]),
    ("privacy-concern", "Privacy Concern", "privacy_concern", "both",
     "로봇의 센싱·기록으로 인한 프라이버시 염려.",
     ["회피·차단 행동"], ["프라이버시 염려 척도"], ["촬영·기록이 걱정되는가?"], ["카메라·기록 고지 조작"]),
    ("proxemics", "Human-Robot Proxemics", "perceived_safety", "both",
     "인간-로봇 간 편안한 물리적 거리.",
     ["유지 거리", "회피 시작 거리"], [], ["어느 거리부터 불편했는가?"], ["접근 거리·속도"]),
    ("intention-understanding", "Intention Understanding", "intention_understanding", "autonomous_delivery_robot",
     "로봇의 다음 행동·의도를 이용자가 예측·이해하는 정도. eHMI 설계와 직결.",
     ["예측 정확도", "주저·혼란"], [], ["로봇이 무엇을 하려는지 알 수 있었는가?"], ["eHMI(신호등·방향표시) 유무"]),
    ("long-term-interaction", "Long-Term Interaction", "acceptance", "care_robot",
     "반복·장기 사용에 따른 태도·행동 변화(신기성 효과 소멸 등).",
     ["사용 빈도 추이", "이탈"], [], ["시간이 지나며 느낌이 어떻게 변했는가?"], ["사용 기간"]),
    ("care-burden", "Care Burden", "care_burden", "care_robot",
     "돌봄로봇이 돌봄제공자의 부담을 경감/가중하는 정도.",
     ["돌봄 시간·스트레스 변화"], ["돌봄부담 척도(ZBI 등)"], ["돌봄 부담이 줄었는가?"], ["로봇 보조 기능 수준"]),
    ("emotional-response", "Emotional Response", "emotional_response", "care_robot",
     "로봇 상호작용에서 유발되는 정서(애착·불쾌·위안 등).",
     ["표정·발화 정서"], ["정서 평정"], ["어떤 감정이 들었는가?"], ["로봇 정서표현 조작"]),
]

STUDY_DESIGNS = [
    {"slug": "field-observation-delivery-robot-pedestrian", "title": "Field Observation of Delivery Robot–Pedestrian Interaction",
     "data": {"robotType": "autonomous_delivery_robot", "studyType": "field_observation",
        "researchBackground": "보도 위 배송로봇과 보행자의 자연스러운 상호작용·상충을 현장에서 관찰. 성수동 관찰연구의 설계.",
        "researchQuestions": ["보행자-로봇 상호작용 유형과 빈도는?", "어떤 상황에서 상충·회피가 발생하는가?", "지각된 안전에 영향을 주는 요인은?"],
        "hypotheses": ["좁은 보도·고밀에서 상충이 증가한다", "로봇의 양보·감속이 회피 거리를 늘린다"],
        "targetParticipantsOrSubjects": ["보행자", "배송로봇", "운영자"],
        "siteContext": ["성수동 상업지구 보도", "출퇴근/주말 시간대"],
        "independentVariables": ["로봇 행동(양보/속도)", "보도 폭·혼잡도", "시간대"],
        "dependentVariables": ["상호작용 유형", "회피 거리", "지각된 안전(추정)"],
        "controlVariables": ["날씨", "연령대"],
        "scenarios": ["정상 조우", "교차 상황", "정지·양보"],
        "dataCollectionMethods": ["구조화 관찰 코딩", "영상 기록(비식별)", "인터셉트 설문"],
        "instruments": ["observation-coding-sheet-delivery", "perceived-safety-survey-delivery"],
        "analysisPlan": "관찰자 간 신뢰도(κ) 산출 → 기술통계·교차분석 → 상충 요인 로지스틱 회귀.",
        "ethicsChecklist": ["IRB 승인", "공공장소 촬영 고지·비식별", "취약보행자 보호"],
        "expectedOutputs": ["상호작용 유형 분류", "보도 운행 가이드 시사점"],
        "policyImplications": ["보도 운행 속도·양보 규칙", "취약보행자 보호 기준"],
        "relatedCases": ["seoul-delivery-robot-sidewalk-pilot", "us-campus-delivery-robots"],
        "relatedSources": ["seoul-sungsu-delivery-robot-observation"]}},
    {"slug": "video-coding-sidewalk-delivery-robot", "title": "Video Coding Protocol for Sidewalk Delivery Robots",
     "data": {"robotType": "autonomous_delivery_robot", "studyType": "video_coding",
        "researchBackground": "현장 영상에서 로봇·보행자 행동을 체계적으로 코딩해 상호작용을 정량화.",
        "researchQuestions": ["행동 코드 간 신뢰도는 확보되는가?", "상충 이벤트의 선행 단서는?"],
        "targetParticipantsOrSubjects": ["영상 속 보행자·로봇"],
        "dependentVariables": ["상호작용 유형", "안전 이벤트"],
        "dataCollectionMethods": ["영상 코딩"], "instruments": ["observation-coding-sheet-delivery"],
        "analysisPlan": "이중 코딩 → Cohen κ → 불일치 합의 → 빈도·시퀀스 분석.",
        "ethicsChecklist": ["비식별", "영상 보관·파기"],
        "policyImplications": ["표준 코딩체계 제안"],
        "relatedCases": ["seoul-delivery-robot-sidewalk-pilot"], "relatedSources": []}},
    {"slug": "scenario-experiment-delivery-robot-ehmi", "title": "Scenario Experiment on Delivery Robot eHMI",
     "data": {"robotType": "autonomous_delivery_robot", "studyType": "field_experiment",
        "researchBackground": "로봇 외부 인터페이스(eHMI)가 의도 이해·지각된 안전에 미치는 영향을 시나리오 실험으로 검증.",
        "researchQuestions": ["eHMI 유무가 의도 이해·지각된 안전을 높이는가?"],
        "hypotheses": ["eHMI 제시 시 의도 이해와 지각된 안전이 향상된다"],
        "targetParticipantsOrSubjects": ["보행자 참여자"],
        "siteContext": ["통제된 보도 구간"],
        "independentVariables": ["eHMI 조건(유/무/유형)"],
        "dependentVariables": ["intention-understanding", "perceived-safety"],
        "controlVariables": ["접근 속도", "거리"],
        "scenarios": ["정면 조우", "교차", "추월"],
        "dataCollectionMethods": ["사후 설문", "행동 측정"],
        "instruments": ["perceived-safety-survey-delivery"],
        "analysisPlan": "조건 간 ANOVA·혼합모형.",
        "ethicsChecklist": ["고지된 동의", "안전관리"],
        "policyImplications": ["eHMI 설계 가이드"],
        "relatedCases": ["seoul-delivery-robot-sidewalk-pilot"], "relatedSources": []}},
    {"slug": "care-robot-trust-experiment-older-adults", "title": "Care Robot Trust Experiment with Older Adults",
     "data": {"robotType": "care_robot", "studyType": "lab_experiment",
        "researchBackground": "돌봄로봇의 상호작용 설계가 고령자의 신뢰·수용성에 미치는 영향을 실험.",
        "researchQuestions": ["친사회적 상호작용이 신뢰를 높이는가?"],
        "hypotheses": ["친사회적 조건이 신뢰·수용성을 높인다"],
        "targetParticipantsOrSubjects": ["65세 이상 고령자"],
        "siteContext": ["실험실/복지관"],
        "independentVariables": ["상호작용 조건(친사회/중립)"],
        "dependentVariables": ["trust-in-hri", "acceptance", "emotional-response"],
        "controlVariables": ["사전 로봇 경험", "연령"],
        "scenarios": ["안부 대화", "복약 알림", "돌발 상황"],
        "dataCollectionMethods": ["사전사후 설문", "행동 측정", "면접"],
        "instruments": ["hri-acceptance-survey-care"],
        "analysisPlan": "집단 간 비교(ANOVA)·조절효과 분석.",
        "ethicsChecklist": ["IRB", "고령자 보호", "중단권"],
        "policyImplications": ["돌봄로봇 상호작용 설계 기준"],
        "relatedCases": ["seoul-care-robot-service-trial"], "relatedSources": []}},
    {"slug": "care-robot-acceptance-welfare-center", "title": "Care Robot Acceptance Study in Welfare Centers",
     "data": {"robotType": "care_robot", "studyType": "survey",
        "researchBackground": "복지관 도입 돌봄로봇에 대한 고령자·종사자 수용성 조사.",
        "researchQuestions": ["수용성의 결정요인은?"],
        "targetParticipantsOrSubjects": ["복지관 이용 고령자", "종사자"],
        "siteContext": ["노인복지관"],
        "dependentVariables": ["acceptance", "perceived-safety", "care-burden"],
        "dataCollectionMethods": ["설문조사"], "instruments": ["hri-acceptance-survey-care"],
        "analysisPlan": "수용성 예측 회귀/SEM.",
        "ethicsChecklist": ["IRB", "동의"], "policyImplications": ["도입 확산 전략"],
        "relatedCases": ["seoul-care-robot-service-trial"], "relatedSources": []}},
    {"slug": "longitudinal-care-robot-use", "title": "Long-Term Care Robot Use Study",
     "data": {"robotType": "care_robot", "studyType": "mixed_methods",
        "researchBackground": "장기 사용에 따른 태도·상호작용 변화(신기성 효과 소멸)를 추적.",
        "researchQuestions": ["시간에 따라 수용성·사용이 어떻게 변하는가?"],
        "targetParticipantsOrSubjects": ["가정 내 고령자"],
        "siteContext": ["가정"],
        "dependentVariables": ["long-term-interaction", "acceptance", "emotional-response"],
        "dataCollectionMethods": ["반복 설문", "사용 로그", "주기적 면접"],
        "analysisPlan": "성장곡선/혼합모형 + 종단 주제분석.",
        "ethicsChecklist": ["IRB", "가정 내 프라이버시", "데이터 파기"],
        "policyImplications": ["지속 사용 지원 서비스 설계"],
        "relatedCases": ["seoul-care-robot-service-trial", "tokyo-care-robot-eldercare"], "relatedSources": []}},
    {"slug": "mixed-methods-care-robot-services", "title": "Mixed-Methods Evaluation of Care Robot Services",
     "data": {"robotType": "care_robot", "studyType": "mixed_methods",
        "researchBackground": "돌봄로봇 서비스의 효과를 정량·정성 통합으로 평가.",
        "researchQuestions": ["서비스가 돌봄 결과·부담에 미치는 효과는?"],
        "targetParticipantsOrSubjects": ["고령자", "돌봄제공자"],
        "dependentVariables": ["care-burden", "acceptance", "emotional-response"],
        "dataCollectionMethods": ["설문", "면접", "관찰"],
        "analysisPlan": "삼각검증(triangulation).",
        "ethicsChecklist": ["IRB", "동의"], "policyImplications": ["서비스 모델·조달 기준"],
        "relatedCases": ["seoul-care-robot-service-trial"], "relatedSources": []}},
]

OBSERVATION_PROTOCOLS = [
    {"slug": "obs-protocol-delivery-robot-sidewalk", "title": "Sidewalk Delivery Robot Observation Protocol",
     "data": {"robotType": "autonomous_delivery_robot", "observationSetting": "sidewalk",
        "purpose": "보도 위 배송로봇-보행자 상호작용·상충을 표준 절차로 관찰.",
        "researchQuestions": ["상호작용 유형·빈도는?", "상충 선행 조건은?"],
        "contextVariables": ["시간대", "보도 폭", "보행 밀도", "날씨"],
        "robotBehaviorVariables": ["속도", "양보", "정지", "경로변경", "eHMI 신호"],
        "humanBehaviorVariables": ["회피 방향", "감속/정지", "주시·촬영", "접촉"],
        "interactionTypes": ["무상호작용 통과", "상호 양보", "경합", "근접 회피", "정지 대치"],
        "conflictCriteria": ["급정지", "경로 봉쇄", "근접(<0.5m) 통과", "접촉", "회피 실패"],
        "samplingStrategy": "시간 표집(피크/비피크) + 사건 표집.",
        "observationUnit": "1 조우(encounter)",
        "recordingPlan": "고정·이동 카메라, 비식별 처리, 보관기간 한정.",
        "privacyProtectionPlan": "얼굴·차량번호 비식별, 공공장소 촬영 고지.",
        "codingProcedure": "2인 독립 코딩 → κ 산출 → 불일치 합의.",
        "analysisPlan": "기술통계·시퀀스·상충 요인 분석.",
        "exportFormats": ["markdown", "csv"]}},
    {"slug": "obs-protocol-care-robot-facility", "title": "Care Robot Facility Observation Protocol",
     "data": {"robotType": "care_robot", "observationSetting": "welfare_center",
        "purpose": "복지시설 내 돌봄로봇-고령자 상호작용 관찰.",
        "researchQuestions": ["상호작용 빈도·질은?", "지속 사용 패턴은?"],
        "contextVariables": ["활동 유형", "동반 종사자 유무", "시간대"],
        "robotBehaviorVariables": ["발화", "이동", "표정·정서표현"],
        "humanBehaviorVariables": ["접근/회피", "대화", "정서표현"],
        "interactionTypes": ["대화·교감", "과업 협조", "무관심", "거부"],
        "conflictCriteria": ["회피·거부", "혼란·불안"],
        "samplingStrategy": "활동 세션 단위 표집.",
        "observationUnit": "1 상호작용 에피소드",
        "recordingPlan": "동의 기반 녹화, 비식별.",
        "privacyProtectionPlan": "건강·민감정보 분리·보호.",
        "codingProcedure": "행동·정서 코딩, 신뢰도 산출.",
        "analysisPlan": "빈도·질적 코딩 통합.",
        "exportFormats": ["markdown"]}},
]

EXPERIMENT_PROTOCOLS = [
    {"slug": "exp-protocol-delivery-robot-ehmi", "title": "Delivery Robot eHMI Scenario Experiment Protocol",
     "data": {"robotType": "autonomous_delivery_robot", "experimentType": "scenario_based_experiment",
        "researchQuestions": ["eHMI가 의도 이해·지각된 안전을 높이는가?"],
        "hypotheses": ["eHMI 제시가 의도 이해·지각된 안전을 향상"],
        "participantCriteria": ["성인 보행자", "검정력 기반 표본"],
        "experimentalConditions": ["eHMI 없음", "방향표시 eHMI", "신호등형 eHMI"],
        "scenarios": ["정면 조우", "교차", "추월"],
        "independentVariables": ["eHMI 조건"],
        "dependentVariables": ["intention-understanding", "perceived-safety"],
        "controlVariables": ["접근 속도", "거리"],
        "measurementInstruments": ["perceived-safety-survey-delivery"],
        "surveyItems": ["의도 이해 문항", "지각된 안전 문항"],
        "interviewQuestions": ["어떤 신호가 도움이 되었는가?"],
        "ethicsConsiderations": ["고지된 동의", "안전관리"],
        "analysisPlan": "조건 간 ANOVA·혼합모형."}},
    {"slug": "exp-protocol-care-robot-trust", "title": "Care Robot Trust Experiment Protocol",
     "data": {"robotType": "care_robot", "experimentType": "lab_experiment",
        "researchQuestions": ["친사회적 상호작용이 신뢰·수용성을 높이는가?"],
        "hypotheses": ["친사회 조건이 신뢰를 높인다"],
        "participantCriteria": ["65세 이상 고령자"],
        "experimentalConditions": ["친사회적", "중립/기능적"],
        "scenarios": ["안부 대화", "복약 알림", "돌발 대응"],
        "independentVariables": ["상호작용 조건"],
        "dependentVariables": ["trust-in-hri", "acceptance", "emotional-response"],
        "controlVariables": ["연령", "사전 경험"],
        "measurementInstruments": ["hri-acceptance-survey-care"],
        "surveyItems": ["신뢰 문항", "수용성 문항"],
        "interviewQuestions": ["로봇을 신뢰했는가? 이유는?"],
        "ethicsConsiderations": ["IRB", "고령자 보호", "중단권"],
        "analysisPlan": "ANOVA·조절효과."}},
]

INSTRUMENTS = [
    {"slug": "observation-coding-sheet-delivery", "title": "Delivery Robot–Pedestrian Observation Coding Sheet",
     "data": {"instrumentType": "video_coding_sheet", "robotType": "autonomous_delivery_robot",
        "relatedHRIConstructs": ["perceived-safety", "proxemics", "intention-understanding"],
        "targetUsers": ["연구자", "코더"],
        "content": "맥락·로봇행동·인간행동·상호작용유형·안전사건·결과 변수를 코드화한 관찰 시트. 2인 코딩·신뢰도 산출용.",
        "exportFormats": ["markdown", "csv"],
        "relatedStudyDesigns": ["field-observation-delivery-robot-pedestrian", "video-coding-sidewalk-delivery-robot"],
        "sources": ["seoul-sungsu-delivery-robot-observation"]}},
    {"slug": "perceived-safety-survey-delivery", "title": "Perceived Safety Survey (Delivery Robot)",
     "data": {"instrumentType": "survey_items", "robotType": "autonomous_delivery_robot",
        "relatedHRIConstructs": ["perceived-safety", "trust-in-hri", "intention-understanding"],
        "targetUsers": ["보행자 참여자"],
        "content": "보도에서 배송로봇과 조우 시 지각된 안전·신뢰·의도 이해를 측정하는 리커트 문항 세트.",
        "exportFormats": ["markdown"], "relatedStudyDesigns": ["scenario-experiment-delivery-robot-ehmi"], "sources": []}},
    {"slug": "hri-acceptance-survey-care", "title": "Care Robot Acceptance & Trust Survey",
     "data": {"instrumentType": "survey_items", "robotType": "care_robot",
        "relatedHRIConstructs": ["acceptance", "trust-in-hri", "social-presence", "care-burden"],
        "targetUsers": ["고령자", "돌봄제공자"],
        "content": "돌봄로봇 수용성·신뢰·사회적 실재감·돌봄부담을 측정하는 설문(UTAUT 기반 수정).",
        "exportFormats": ["markdown"], "relatedStudyDesigns": ["care-robot-trust-experiment-older-adults",
                                                                 "care-robot-acceptance-welfare-center"], "sources": []}},
    {"slug": "hri-interview-guide", "title": "HRI Semi-Structured Interview Guide",
     "data": {"instrumentType": "interview_guide", "robotType": "both",
        "relatedHRIConstructs": ["trust-in-hri", "acceptance", "emotional-response", "privacy-concern"],
        "targetUsers": ["이용자", "보행자", "고령자"],
        "content": "로봇 경험·신뢰·불안·프라이버시·개선요구를 탐색하는 반구조화 면접 가이드.",
        "exportFormats": ["markdown"], "relatedStudyDesigns": [], "sources": []}},
]

POLICY_ISSUES = [
    {"slug": "sidewalk-robot-governance", "title": "Sidewalk Delivery Robot Governance", "data": {
        "robotType": "autonomous_delivery_robot", "policyDomain": "sidewalk_governance",
        "issueDefinition": "보도라는 보행 공간에서 배송로봇의 통행·속도·우선순위를 어떻게 규율할 것인가.",
        "whyItMatters": "보행안전과 라스트마일 효율이 충돌하는 핵심 지점. 보행 약자 보호와 직결.",
        "internationalTrends": ["보도 통행 허용 입법(한국 2023)", "속도·중량 제한", "운행구역 지정"],
        "keyCases": ["seoul-delivery-robot-sidewalk-pilot", "us-campus-delivery-robots"],
        "policyOptions": ["속도·중량 상한", "운행시간·구역 제한", "양보·우선 규칙", "취약보행자 보호구역"],
        "seoulImplications": "보행친화 정책과의 정합성 확보, 성수동 실증 근거 활용.",
        "relatedResearchQuestions": ["속도·양보 규칙이 지각된 안전을 얼마나 높이는가?"],
        "sources": ["korea-sidewalk-robot-act"]}},
    {"slug": "robot-safety-liability", "title": "Robot Safety & Liability", "data": {
        "robotType": "both", "policyDomain": "liability",
        "issueDefinition": "로봇 사고 시 책임 귀속과 안전기준·인증 체계.",
        "whyItMatters": "사고 책임의 불확실성은 도입과 수용을 저해.",
        "internationalTrends": ["운행안전 인증", "보험 의무화", "사고기록장치"],
        "keyCases": ["seoul-delivery-robot-sidewalk-pilot"],
        "policyOptions": ["안전인증 기준", "의무보험", "사고 데이터 기록·공개"],
        "seoulImplications": "보험·인증 체계 정비로 실증 확산 지원.",
        "relatedResearchQuestions": ["안전사건 빈도·심각도의 실측은?"], "sources": []}},
    {"slug": "robot-privacy-data", "title": "Robot Privacy & Data Governance", "data": {
        "robotType": "both", "policyDomain": "privacy",
        "issueDefinition": "로봇의 센싱·영상·건강데이터 수집에 대한 프라이버시·데이터 거버넌스.",
        "whyItMatters": "공공장소·가정 내 상시 센싱은 프라이버시 침해 우려를 야기.",
        "internationalTrends": ["촬영 고지·비식별", "데이터 최소수집", "동의 기반 처리"],
        "keyCases": ["seoul-care-robot-service-trial"],
        "policyOptions": ["비식별 의무", "보관·파기 기준", "투명성 고지"],
        "seoulImplications": "S-DoT 등 데이터 정책과 연계한 가이드라인.",
        "relatedResearchQuestions": ["프라이버시 염려가 수용성에 미치는 영향은?"], "sources": []}},
    {"slug": "care-robot-ethics", "title": "Care Robot Ethics", "data": {
        "robotType": "care_robot", "policyDomain": "care_ethics",
        "issueDefinition": "돌봄로봇이 인간 돌봄을 보완/대체할 때의 존엄·자율성·정서적 영향 문제.",
        "whyItMatters": "취약한 고령자의 존엄과 관계의 질에 직접 영향.",
        "internationalTrends": ["인간 돌봄 보완 원칙", "기만적 의인화 경계", "이용자 자율성"],
        "keyCases": ["seoul-care-robot-service-trial", "tokyo-care-robot-eldercare"],
        "policyOptions": ["윤리 가이드라인", "인간-로봇 역할 구분", "동의·선택권 보장"],
        "seoulImplications": "커뮤니티케어와 결합한 윤리 기준 마련.",
        "relatedResearchQuestions": ["로봇 돌봄이 정서·관계의 질에 미치는 영향은?"], "sources": []}},
    {"slug": "robot-public-acceptance", "title": "Public Acceptance of Urban Robots", "data": {
        "robotType": "both", "policyDomain": "public_acceptance",
        "issueDefinition": "도시 공공공간에서 로봇 운용에 대한 시민 수용성과 신뢰 확보.",
        "whyItMatters": "낮은 수용성은 도입 지속가능성을 위협.",
        "internationalTrends": ["시민 참여·소통", "투명한 정보공개", "단계적 실증"],
        "keyCases": ["seoul-delivery-robot-sidewalk-pilot"],
        "policyOptions": ["시민 소통·참여", "정보 공개", "민원·피드백 체계"],
        "seoulImplications": "실증 단계의 시민 소통 전략.",
        "relatedResearchQuestions": ["수용성의 핵심 결정요인은?"], "sources": []}},
]


# ---------- 조립 ----------
def _wc(kind, items):
    return [{"subsystem": "worldcities", "kind": kind, "slug": it["slug"], "title": it["title"], "data": it["data"]}
            for it in items]


def _topic_records():
    out = []
    for slug, title, cat, definition, issues in WORLD_TOPICS:
        out.append({"subsystem": "worldcities", "kind": "topic", "slug": slug, "title": title,
                    "data": {"topicCategory": cat, "definition": definition, "keyIssues": issues,
                             "relatedCities": [], "relatedCases": [], "relatedRobotTopics": [],
                             "researchQuestions": [], "policyImplications": [], "sources": []}})
    return out


def _hri_records():
    out = []
    for slug, title, cat, applies, definition, indic, surveys, interviews, expvars in HRI_CONSTRUCTS:
        out.append({"subsystem": "urbanrobotics", "kind": "hri", "slug": slug, "title": title,
                    "data": {"constructCategory": cat, "definition": definition, "applicableRobotTypes": applies,
                             "observableIndicators": indic, "surveyMeasures": surveys,
                             "interviewQuestions": interviews, "experimentalVariables": expvars,
                             "relatedMethods": [], "relatedCases": [], "sources": []}})
    return out


def _ur(kind, items):
    return [{"subsystem": "urbanrobotics", "kind": kind, "slug": it["slug"], "title": it["title"], "data": it["data"]}
            for it in items]


RECORDS = (
    _wc("city", WORLD_CITIES)
    + _topic_records()
    + _wc("case", WORLD_CASES)
    + _wc("policy", WORLD_POLICIES)
    + _ur("robottype", ROBOT_TYPES)
    + _ur("robotcase", ROBOT_CASES)
    + _hri_records()
    + _ur("studydesign", STUDY_DESIGNS)
    + _ur("observation", OBSERVATION_PROTOCOLS)
    + _ur("experiment", EXPERIMENT_PROTOCOLS)
    + _ur("instrument", INSTRUMENTS)
    + _ur("policyissue", POLICY_ISSUES)
)
