# -*- coding: utf-8 -*-
"""세계대도시협력(WPSC) 서브시스템 게시판 데이터.

세 구분: 국외 출장(trips) · 연구원 내원(visits) · 글로벌 협력기관(partners)
+ 진행상황 타임라인(progress). 대외협력 폴더(국제기구·진행상황·출장및행사) 정리.
국외출장 항목 중 wpsc=True 는 기존 WPSC 일정 페이지(/wpsc/itinerary)로 연결.
"""

WPSC = {
    "trips": [
        {"title": "제6회 세계도시계획대학총회(WPSC 2026)", "date": "2026.06", "city": "헬싱키·에스포", "country": "핀란드",
         "purpose": "구두발표 및 GPEAN 네트워킹", "wpsc": True,
         "summary": "최준영 선임연구위원이 WPSC 2026(헬싱키·에스포)에 참가, 구두발표 1편(ID 1385, Track 1: 보행 중심 생활권 내 인구구조 변화 대응 최적 편의시설 배치). 6.30(화) 세션 발표, 탐페레 답사·칼라사타마 스마트시티 견학 병행(6.27~7.5)."},
        {"title": "CES 2026 참가", "date": "2026.01", "city": "라스베이거스", "country": "미국",
         "purpose": "글로벌 AI·스마트시티 기술 동향 조사", "wpsc": False,
         "summary": "최준영 센터장이 CES 2026 참가(Industry Attendee), 최신 AI·스마트시티 기술 동향 조사 후 국제협력 전략 수립에 활용."},
        {"title": "상하이 대도시컨퍼런스(MPIC) · SUPDRI 방문", "date": "2025.12", "city": "상하이", "country": "중국",
         "purpose": "MeTTA 협력·공동연구 착수 · MOU 협의", "wpsc": False,
         "summary": "상하이 MPIC 참가 및 SUPDRI 방문(12.5~). AI 시민페르소나 플랫폼 연구 발표, 서울연-SUPDRI MOU 체결 절차 및 데이터·공동연구 협력 협의."},
        {"title": "CUPUM 2025 학술발표 (런던 UCL)", "date": "2025.06", "city": "런던", "country": "영국",
         "purpose": "AI 기반 도시계획 학술발표 · 네트워킹", "wpsc": False,
         "summary": "최준영 연구위원이 UCL CUPUM 2025 참가(6.22~29), AI 기반 도시계획 연구 발표. Mike Batty 강연 수강·레치워스 전원도시 답사."},
        {"title": "도쿄 모리재단·도쿄도청·NSRI 출장", "date": "2025.06", "city": "도쿄", "country": "일본",
         "purpose": "도시경쟁력 지표 교류 · MeTTA 가입 협의", "wpsc": False,
         "summary": "서울시·서울연 대표단이 NSRI·도쿄도청 디지털개혁과·모리기념재단 방문(6.3~5). 도보가능지수 공동연구 관심 확인, MeTTA 가입·총회 협의, 신도정(DX) 행정혁신 벤치마킹."},
        {"title": "FOSS4G KANSAI 2025", "date": "2025.07", "city": "간사이", "country": "일본",
         "purpose": "개방형 공간정보 국제협력 발표", "wpsc": False,
         "summary": "최준영 연구위원이 FOSS4G KANSAI 2025 참가(7.4~6), 'FOSS4G 다자간 협력' 발표. 서울시 공간정보 국제협력·MeTTA 연계 소개."},
        {"title": "보고타 폐기물관리 전문가그룹(EGM)", "date": "2025.03", "city": "보고타", "country": "콜롬비아",
         "purpose": "UN-Habitat·보고타시 EGM 토론 · 대도시 네트워크", "wpsc": False,
         "summary": "보고타 폐기물관리 EGM 참가(3.27~28, UAESP·UN-Habitat 공동주관). 고형폐기물·메트로폴리탄 확장 세션 토론, AMB·IPR·마르마라연합과 네트워크, Renobo 도시재생 현장 답사."},
        {"title": "바르셀로나 디지털메트로폴리스 전문가회의(EGM)", "date": "2025.01", "city": "바르셀로나", "country": "스페인",
         "purpose": "AMB·UN-Habitat 디지털메트로폴리스 EGM", "wpsc": False,
         "summary": "AMB·UN-Habitat 공동주관 디지털메트로폴리스 EGM 참가(1.20~21). 디지털 인프라·데이터 알고리즘 투명성·솔루션 구현 세션 토론, 바르셀로나 슈퍼컴센터 견학."},
        {"title": "WUF12 제12차 세계도시포럼 (카이로)", "date": "2024.11", "city": "카이로", "country": "이집트",
         "purpose": "AI 시대 대도시계획 세션 공동주관", "wpsc": False,
         "summary": "WUF12 참가(11.3~10). 서울연·파리지역연구원 '디지털 시대의 계획 정직성' 세션 공동주관. 이집트 HBRC·호치민 UEH·이스탄불 등 메가시티 계획기관 참여."},
        {"title": "사우디 글로벌 AI 서밋(GAIN)", "date": "2024.09", "city": "리야드", "country": "사우디아라비아",
         "purpose": "SDAIA GAIN 패널토론 · AI 도시계획 발표", "wpsc": False,
         "summary": "SDAIA 제3회 GAIN(9.10~12) 패널토론(AI's Civic Duty) 참가. 서울시·연세대·네이버 동반, UN-ITU AI for Good·위성영상 기업 미팅, Vision 2030 AI 전략 조사."},
    ],
    "visits": [
        {"title": "파리지역연구원(IPR) 방문단 내원", "date": "2026.06", "who": "프랑스 · Institut Paris Region",
         "summary": "IPR 대표단이 서울연 정동청사 방문(6.4). 일드프랑스 신광역마스터플랜 발표, MOU 후속 협력·WUF13 공동세션 최종 준비 협의(윤서연 박사 연락관)."},
        {"title": "파리지역연구원(IPR) MOU 체결·연구교류", "date": "2025.09", "who": "프랑스 · Institut Paris Region",
         "summary": "서울연–IPR MOU 체결(9월) 및 연구교류. 도시계획·정책연구 협력·공동연구·연구자 상호방문 포함. 후속 WUF13 공동세션·주택지표 공동보고서 기획."},
        {"title": "키르기즈공화국 공무원 초청연수단", "date": "2026.05", "who": "키르기즈공화국 · 공무지방자치청 외 12~14인",
         "summary": "공무지방자치청 연수단이 서울연 방문(5.14). 서울시 공무원 성과평가제도·도시행정 강연 수강. 대통령실 부국장 등 인사·평가·디지털개발 담당, 한국 인사행정 벤치마킹."},
        {"title": "두바이 의회·상공회의소 대표단(WUF13 사전면담)", "date": "2026.05", "who": "UAE · 두바이 의회사무국+상공회의소 4인",
         "summary": "두바이 의회사무국장 외 4인이 WUF13 개최 중 서울연 방문(5.19). 2026.10 두바이 CEO급 고위급 방한에 앞선 실무 사전면담, 연구프로그램·협력의제 논의."},
        {"title": "노르웨이 아그더대학(EU Agorus) 연구자 면담", "date": "2026.03", "who": "노르웨이 · 아그더대학 Phylicia Babb 박사",
         "summary": "아그더대학 박사연구원이 정동청사 방문(3.27). 메타버스 서울·S-Map 디지털트윈 거버넌스 인터뷰(EU Horizon Agorus 프로젝트). 최준영·최수범·김현, 서울시 김선화 주무관 참석."},
        {"title": "도쿄도 국제협력담당관 내한 세미나", "date": "2026.02", "who": "일본 · 도쿄도 도지사정책기획실 4인",
         "summary": "도쿄도 외교담당과 부과장 외 3인이 서울 방문(2.10~12) 정책교류 세미나. 신도정(Shin-Tosei) 행정혁신·인구 집중 연구 소개, 창의행정·도시경쟁력 지수 교류."},
        {"title": "태국 중앙공무원위원회(PSAC) 정책교류 세미나", "date": "2026.02", "who": "태국 · 중앙공무원위원회(PSAC)",
         "summary": "PSAC 대표단 서울연 방문 정책교류 세미나(2.5). 미래공간연구실 김상일 박사 발제, 서울연 소개 및 AI 기반 도시정책 형성 사례 공유, 메가시티 거버넌스·행정혁신 양국 사례 교류."},
        {"title": "두바이시청 방문단 · MOU 체결식", "date": "2025.10", "who": "UAE · 두바이시청 사무총장 외 6인",
         "summary": "두바이시청 사무총장 마르완 빈 갈리타 외 6인이 서울연 방문 MOU 체결(10.2). 데이터 기반 도시정책·지식교류·공동연구·국제세미나(3년). 스마트라이프위크 기간 공식 초청."},
        {"title": "이스라엘 사회복지부 차관 방문", "date": "2025.10", "who": "이스라엘 · 사회복지부 이논 아하로니 차관",
         "summary": "이스라엘 사회복지부 차관이 서울연 방문(10.27). 사회복지·도시 복지서비스 분야 한-이스라엘 정책 교류."},
        {"title": "타이페이시 연구개발심사위원회 방문", "date": "2024.10", "who": "대만 · 타이페이시 연구개발심사위 5인",
         "summary": "타이페이시정부 연구개발심사위 전문위원 외 4인이 서울연 집현실 방문(10.24). 연구현황·미래시정 비전·연구심사 기능·정책 반영 체계 질의응답."},
        {"title": "Carlos Moreno 교수 초청 세미나(15분 도시)", "date": "2024.05", "who": "프랑스 · 파리 소르본 Chaire ETI",
         "summary": "'15분 도시' 창시자 Carlos Moreno 교수 초청 세미나(5.27). '노령사회 대비 보행일상권 계획' 서울·파리 공동발표, 서울연-Chaire ETI MOU 동시 체결(국토도시계획학회 공동주최)."},
        {"title": "Jeroen van der Heijden 교수 초청 세미나(포스트탄소도시)", "date": "2024.03", "who": "호주·뉴질랜드 · ANU/Victoria(Wellington)",
         "summary": "Jeroen van der Heijden 교수 초청 포스트탄소도시 세미나(3.19). 20년간 도시 기후행동·거버넌스 사례 기반 탈탄소 전환 전략 논의."},
    ],
    "partners": [
        {"org_kr": "메가시티 싱크탱크 얼라이언스(MeTTA)", "org_en": "Metropolis Think Tank Alliance (MeTTA)", "city": "서울(사무국)", "country": "글로벌 네트워크",
         "type": "network", "relationship": "사무국",
         "summary": "세계 메가시티 도시계획 싱크탱크 다자 협력체. 서울연구원이 사무국. 2025.9 제9회 총회(서울)에서 파리지역연구원(IPR)·모리재단·아랍도시개발연구원(AUDI)·닛켄세키 신규 가입, 2026.10 제10회 총회 베이징 개최. WUF13(바쿠, 2026.5)에서 MeTTA 세션 '주택위기와 메가시티 역할: 공동 주택지표 프레임워크' 조직·운영(서울연·IPR·SUPDRI·AUDI·마르마라연합 공동). 공동연구 주제 'AI와 메가시티 계획'.",
         "keywords": ["MeTTA", "싱크탱크얼라이언스", "WUF13", "주택지표", "사무국"]},
        {"org_kr": "유엔해비타트(UN-Habitat) / MetroHUB", "org_en": "UN-Habitat", "city": "나이로비", "country": "케냐",
         "type": "international_org", "relationship": "네트워크",
         "summary": "유엔 인간정주 전문기구. WUF10·11·12 참가, MetroHUB 공동기고, 책임있는 AI 전문가회의(2023) 협력. MeTTA 총회 성과를 MetroHUB로 전파하는 핵심 파트너. WSSD25 사이드이벤트 공동 제안.",
         "keywords": ["WUF", "MetroHUB", "스마트도시 가이드라인", "책임있는AI", "세계도시포럼"]},
        {"org_kr": "두바이 시청", "org_en": "Dubai Municipality", "city": "두바이", "country": "UAE",
         "type": "city_government", "relationship": "MoU",
         "summary": "2025.10 MoU, 2026.02 공동연구협정(PSA) 체결. 폐기물 관리·일상 오픈스페이스 두 주제로 서울-두바이 병행 케이스스터디(2026 상반기), 공동 발표·보고서 출판 및 방한 면담 예정.",
         "keywords": ["MoU", "공동연구", "폐기물관리", "오픈스페이스", "PSA"]},
        {"org_kr": "싱가포르 CLC / 리콴유세계도시상 네트워크", "org_en": "Centre for Liveable Cities (CLC) / LKYWCP", "city": "싱가포르", "country": "싱가포르",
         "type": "research_institute", "relationship": "네트워크",
         "summary": "싱가포르 국가개발부 산하 도시연구기관. 서울은 리콴유세계도시상 수상도시 네트워크(15개 도시)의 서울 대표 지식기관으로 공식 지정. 지속가능 도시 우수사례 교류, 2026.2 교류 계획.",
         "keywords": ["리콴유세계도시상", "LKYWCP", "지속가능도시", "도시지식네트워크"]},
        {"org_kr": "메트로폴리스 솔루션랩", "org_en": "Metropolis – World Association of the Major Metropolises", "city": "바르셀로나", "country": "스페인",
         "type": "network", "relationship": "네트워크",
         "summary": "150여 메가시티 회원 세계대도시협회. 서울 정회원, 2024 솔루션랩(시티버스 메타버스) 참여. 2025.9 제40차 총회 서울 개최(MeTTA 병행). 거버넌스·기후·젠더형평 등 5대 테마 교류.",
         "keywords": ["Metropolis", "솔루션랩", "메가시티", "시티버스"]},
        {"org_kr": "이클레이(ICLEI) 동아시아 본부", "org_en": "ICLEI East Asia", "city": "서울", "country": "대한민국",
         "type": "network", "relationship": "네트워크",
         "summary": "지속가능 지방정부 국제네트워크 이클레이 동아시아 사무소(서울 소재). 사실상 상주 협력. 기후·생물다양성·전기모빌리티 국제회의·행사 협력.",
         "keywords": ["ICLEI", "지속가능성", "지방정부", "기후변화"]},
        {"org_kr": "모리기념재단", "org_en": "Mori Memorial Foundation", "city": "도쿄", "country": "일본",
         "type": "research_institute", "relationship": "MoU",
         "summary": "2024.12 MoU 체결. 도시경쟁력지수(GPCI) 발간 기관. 대도시 연구 아이디어 공유·컨퍼런스 상호초청·연 2회 화상회의, 2025.9 MeTTA 신규 회원 가입.",
         "keywords": ["모리재단", "MoU", "MeTTA", "도시경쟁력지수(GPCI)"]},
        {"org_kr": "상하이 성시규획설계연구원(SUPDRI)", "org_en": "Shanghai Urban Planning and Design Research Institute", "city": "상하이", "country": "중국",
         "type": "research_institute", "relationship": "MoU",
         "summary": "상하이시 산하 도시계획 연구기관. 2026.4 MoU 체결. 연구데이터 공유·공동 학술회의·전문가 교류·공동연구. 2025.12 경영진 회의~2026.5 뉴스레터 교환.",
         "keywords": ["SUPDRI", "MoU", "도시계획", "공동연구", "MeTTA"]},
        {"org_kr": "베이징 성시규획설계연구원(BICP) / MeTTA 사무국", "org_en": "Beijing Institute of City Planning and Design", "city": "베이징", "country": "중국",
         "type": "research_institute", "relationship": "네트워크",
         "summary": "베이징시 산하 도시계획 연구기관, MeTTA 주요 회원. 2026.10 제10회 MeTTA 총회 베이징 주최, 서울연 사무국 지원·공동 준비(AI와 메가시티·기후리스크·주택재생).",
         "keywords": ["BICP", "MeTTA", "도시계획", "싱크탱크얼라이언스"]},
        {"org_kr": "파리 지역 연구원(IPR)", "org_en": "Institut Paris Region", "city": "파리", "country": "프랑스",
         "type": "research_institute", "relationship": "MoU",
         "summary": "파리 광역권 도시계획 공공연구기관, MTPA 핵심 멤버. 2025.9 MOU 체결, MetroHUB 공동기고, 2025.9 MeTTA 신규 회원. WUF13 공동세션·주택지표 공동보고서 추진.",
         "keywords": ["IPR", "MTPA", "MeTTA", "MetroHUB"]},
        {"org_kr": "네덜란드 응용과학연구기구(TNO)", "org_en": "Netherlands Organisation for Applied Scientific Research", "city": "암스테르담", "country": "네덜란드",
         "type": "research_institute", "relationship": "MoU",
         "summary": "네덜란드 최대 응용과학연구기관. 2023.3 스마트시티 MoU. 예측형 디지털트윈 공동개발, 2024.5 대사관저 만찬 교류. 한-네 정부 간 스마트시티 MoU(2019) 기반.",
         "keywords": ["TNO", "MoU", "디지털트윈", "스마트시티"]},
        {"org_kr": "유엔환경계획(UNEP)", "org_en": "UN Environment Programme", "city": "나이로비", "country": "케냐",
         "type": "international_org", "relationship": "방문교류",
         "summary": "유엔 환경 전문기구. 2024.4 UNEP Gender·Safeguard 팀장 초청 '국제환경정책 실행 과제' 세미나. 환경우선순위·기후-도시 연계 논의, 기후대응 협력 탐색.",
         "keywords": ["UNEP", "기후변화", "환경정책", "국제세미나"]},
        {"org_kr": "호치민 경제대(UEH) 스마트시티연구소(ISCM)", "org_en": "University of Economics Ho Chi Minh City – ISCM", "city": "호치민", "country": "베트남",
         "type": "university", "relationship": "방문교류",
         "summary": "베트남 최상위 경제·경영대학. 2024.5 Nguyen Dong Phong 의장 등 대표단 서울연 방문, 스마트시티 공동연구 논의. ISCM 통한 도시혁신 연구 협력.",
         "keywords": ["UEH", "ISCM", "스마트시티", "베트남"]},
        {"org_kr": "USAID 지리공간 전략", "org_en": "USAID – Geospatial Strategy", "city": "워싱턴 DC", "country": "미국",
         "type": "international_org", "relationship": "협력논의",
         "summary": "미국 국제개발처 지리공간 전략. 개도국 지원에서 GIS 전략 활용 관심. 서울연 빅데이터·공간정보 역량 연계 ODA·국제개발 협력 탐색.",
         "keywords": ["USAID", "지리공간", "GIS", "ODA"]},
        {"org_kr": "보고타 도시재개발공사(RENOBO) / K-City", "org_en": "RENOBO / K-City Network", "city": "보고타", "country": "콜롬비아",
         "type": "city_government", "relationship": "협력논의",
         "summary": "보고타시 산하 도시재개발 기관. 2024 국토부 K-City 네트워크(RENOBO) 통해 몬테비데오 전략구역 지구단위계획 협력 제안. ODA 공모 연계 스마트도시 계획 지원 논의.",
         "keywords": ["RENOBO", "K-City네트워크", "ODA", "도시재개발"]},
        {"org_kr": "아랍 도시개발연구소(AUDI)", "org_en": "Arab Urban Development Institute", "city": "리야드", "country": "사우디아라비아",
         "type": "research_institute", "relationship": "네트워크",
         "summary": "아랍 도시개발 연구기관. 2025.9 제9회 MeTTA 총회에서 IPR·모리재단·닛켄세키와 함께 신규 회원 승인. 중동·아랍권 메가시티 연구 협력 거점.",
         "keywords": ["AUDI", "MeTTA", "아랍도시", "중동"]},
        {"org_kr": "WSSD25 (제2차 세계사회발전정상회의)", "org_en": "UN-Habitat / 2nd World Summit for Social Development", "city": "나이로비", "country": "케냐",
         "type": "international_org", "relationship": "협력논의",
         "summary": "유엔 제2차 사회발전 세계정상회의. 주택·인간안보 사이드이벤트 공동 제안('모두를 위한 주택'+인간안보 프레임워크). 캐나다·노르웨이·일본 등 6개국 상주대표부·UCLG 공동주최.",
         "keywords": ["WSSD25", "주택", "인간안보", "사회발전"]},
        {"org_kr": "국별 ODA 대상국(케냐·인도·필리핀)", "org_en": "ODA Partner Countries", "city": "나이로비/뭄바이/마닐라", "country": "케냐·인도·필리핀",
         "type": "city_government", "relationship": "기타",
         "summary": "건축행정시스템(KAIS)·한국형 스마트시티 금융·KOICA 연계로 한국 도시개발 경험 전수. 케냐(KAIS 수출)·인도(스마트시티 100개 금융연구)·필리핀(KOICA 도시계획 지원).",
         "keywords": ["ODA", "KOICA", "KAIS", "스마트시티"]},
    ],
    "progress": [
        {"period": "2026.6", "summary": "WPSC 2026(헬싱키) 출장 준비·참가 예정. 파리지역연구원 내원(6.4) WUF13 후속·광역마스터플랜 교류. WUF13(바쿠) MeTTA 세션 운영, 두바이 사전면담(5.19)."},
        {"period": "2026.1~5", "summary": "CES 2026(1월). 태국 PSAC 내원(2.5)·방콕 출장. 도쿄도 내한세미나(2.10). 서울연-상하이SUPDRI·싱가포르CLC 화상회의. 노르웨이 아그더대 면담(3.27). 키르기즈 연수단(5.14). MeTTA 실무회의·WUF13 세션(5.17~22)."},
        {"period": "2025.9~12", "summary": "서울연-IPR MOU(9월). 두바이시청 내원·MOU(10.2). 이스라엘 차관 내원(10.27). 상하이 MPIC·SUPDRI MOU 협의(12월). 메트로폴리스 제40차 총회 서울 개최. ITU AI for Good MeTTA 웨비나."},
        {"period": "2025.1~8", "summary": "바르셀로나 EGM(1월)·보고타 EGM(3월). 도쿄 출장(6월) MeTTA 가입 협의. CUPUM UCL(6월)·FOSS4G KANSAI(7월). MeTTA 사무국 글로벌연구협력센터 체제 전환."},
        {"period": "2024", "summary": "WUF12 카이로(11월) AI 대도시계획 세션 공동주관. 사우디 GAIN(9월) 패널. 타이페이 방문단(10.24)·TNO 회의. Carlos Moreno·van der Heijden 해외석학 세미나, Chaire ETI MOU."},
    ],
}

CATEGORIES = [
    {"key": "trips", "kr": "국외 출장", "en": "Overseas Trips", "icon": "✈️"},
    {"key": "visits", "kr": "연구원 내원", "en": "Inbound Visits", "icon": "🤝"},
    {"key": "partners", "kr": "글로벌 협력기관", "en": "Global Partners", "icon": "🌐"},
]
